# Server settings
server:
  port: 8080

spring:
  #DATASOURCE
  datasource:
    url: jdbc:mysql://120.25.192.71:3306/grace
    username: root
    password: w5566
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000 # Number of ms to wait before throwing an exception if no connection is available
      max-active: 50  # Maximum number of active connections that can be allocated from this pool at the same time.
      test-on-borrow: true  # Validate the connection before borrowing it from the pool.
